#!/bin/bash

## Constants ##

RELEASE_HELP="usage: regen [-h | --help]
regenerate the 'full' desk (with dependencies) from the 'bare' desk

Flag arguments:
  -h, --help: show this help message"

## Helper Functions ##

## Arguments ##

while : ; do case ${1} in
	-h | --help) printf "%s\\n" "$RELEASE_HELP" && exit 1 ;;
	-*) printf "invalid option: %s\\n" "${1}" && exit 1 ;;
	*) break ;;
esac done

if [ "0" != "$#" ]; then
	printf "%s\\n" "$RELEASE_HELP" && exit 1
fi

## Processing ##

regen__basedir="$(dirname "$(dirname "$(dirname "$(readlink -f "$0")")")")"
regen__deskdir="${regen__basedir}/desk"

cd "${regen__deskdir}"
rm -rf full/
find bare -type f | while read f; do { d=$(dirname "$f" | sed "s/^bare/full/"); mkdir -p "$d"; ln -sr -t "$d" "$f"; }; done
mkdir -p full/app full/lib/ full/mar full/sur/json full/ted
ln -sr ../LICENSE.txt full/license.txt

git clone -b 411k --depth 1 https://github.com/urbit/urbit.git urb
cp urb/pkg/arvo/lib/{verb*,naive*,tiny*,ethereum*,ethio*,strand*} full/lib/
cp urb/pkg/arvo/sur/{verb*,spider*} full/sur/
cp urb/pkg/arvo/sur/json/rpc* full/sur/json/

git clone -b sl/server-schooner-z412k --depth 1 https://github.com/sidnym-ladrut/yard.git yar
cp yar/desk/lib/{dbug*,default-agent*,skeleton*,rudder*,server*,docket*,mip*} full/lib/
cp yar/desk/mar/{atom*,bill*,docket*,hoon*,json*,kelvin*,mime*,noun*,ship*,txt*,css*,png*,svg*,js*} full/mar/
cp yar/desk/sur/docket* full/sur/

git clone --depth 1 https://github.com/tocwex/make.git mak
cp mak/desk/app/fund-watcher* full/app/
cp mak/desk/mar/fund-watcher* full/mar/
cp mak/desk/sur/fund-watcher* full/sur/
cp mak/desk/ted/fund-watcher* full/ted/

git clone --depth 1 https://github.com/nocsyx-lassul/gin-tonic.git gat
cp gat/tonic/lib/tonic.hoon full/lib/
cp gat/tonic/mar/cass.hoon full/mar/

git clone -b sl/demo-vsss --depth 1 https://github.com/sidnym-ladrut/sss.git sss
cp sss/urbit/lib/sss.hoon full/lib/
cp sss/urbit/sur/sss.hoon full/sur/

git clone -b sl/improve-install-data-reliability --depth 1 https://github.com/sidnym-ladrut/vita.git vit
cp vit/vita-client/lib/vita-client.hoon full/lib/

git clone --depth 1 https://github.com/tinnus-napbus/manx-utils.git mut
cp mut/lib/manx-utils.hoon full/lib/
